import {Platform, StyleSheet} from 'react-native';
import {colors, fontFamily, fontSize} from '../../../helper/utils';
import {hp, wp} from '../../../helper/constants';

const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  rightContainer: {
    paddingLeft: wp(3.5),
  },
  mainContainer: {
    marginBottom: hp(4),
  },
  profileDetailContainer: {
    marginVertical: hp(2.5),
  },
  detailsContainer: {
    marginTop: hp(4),
    marginBottom: hp(5),
  },
  uploadPhotoView: {
    width: '85%',
    paddingVertical: hp(7.5),
    alignSelf: 'center',
    backgroundColor: colors.inputGrey,
    marginTop: hp(3),
    borderRadius: wp(4),
  },
  addIconContainer: {
    alignSelf: 'center',
    justifyContent: 'center',
  },
  addIconStyle: {
    height: wp(4),
    width: wp(4),
    tintColor: colors.darkBlue,
    marginVertical: hp(0.5),
  },
  uploadPhotoTxt: {
    color: colors.darkBlue,
    fontFamily: fontFamily.bold,
    fontSize: fontSize(17),
    alignSelf: 'center',
    marginVertical: hp(1),
  },
  uploadedPhotoView: {
    width: '87%',
    paddingVertical: hp(11),
    alignSelf: 'center',
    backgroundColor: colors.inputGrey,
    marginTop: hp(1),
    borderRadius: wp(4),
  },
  nameAndLocationContainer: {
    width: '55%',
    alignSelf: 'center',
  },
  textInputStyle: {
    fontSize: fontSize(17),
    backgroundColor: colors.inputGrey,
    paddingVertical: Platform.OS === 'android' ? hp(1) : hp(1.5),
    marginVertical: hp(0.7),
    borderRadius: wp(4),
    paddingHorizontal: wp(5),
    textAlignVertical: 'center',
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
  },
  prilePicContainer: {
    position: 'absolute',
    bottom: wp(5),
    alignSelf: 'center',
  },
  outerPicContainer: {
    width: '90%',
    marginHorizontal: wp(5),
    borderRadius: wp(10),
  },

  profilePic: {
    height: wp(43),
    width: '100%',
    borderRadius: wp(5),
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: colors.lightGreen,
  },
  changePhotoTxt: {
    fontFamily: fontFamily.bold,
    color: colors.darkBlue,
    fontSize: fontSize(19),
  },
  changeVideo: {
    position: 'absolute',
    bottom: wp(7),
    alignSelf: 'center',
  },
  midContainer: {
    width: '90%',
    alignSelf: 'center',
  },
  container1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dobGenderContainer: {
    flexDirection: 'row',
    marginHorizontal: wp(5),
    marginVertical: hp(0.5),
  },
  dropDownContainer: {
    backgroundColor: colors.inputGrey,
    justifyContent: 'center',
    borderRadius: wp(4),
    width: '48%',
    marginBottom: hp(2),
    paddingVertical: hp(1.5),
    flex: 1,
  },
  dropDownTitltTxt: {
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    textAlignVertical: 'center',
    flex: 1,
  },
  genderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: wp(7),
  },
  downArrowImg: {
    height: hp(3),
    width: wp(3),
    marginHorizontal: wp(7),
  },
  dropdown: {
    flex: 1,
    backgroundColor: colors.lightGrey,
    borderRadius: wp(4),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
  },
  dropdownLaung: {
    paddingVertical: Platform.OS === 'android' ? hp(0.5) : hp(1),
    marginVertical: hp(0.7),
    marginHorizontal: wp(5),
    borderRadius: wp(4),
    backgroundColor: colors.lightGrey,
    paddingHorizontal: wp(2),
  },
  dropdownSkill: {
    paddingVertical: Platform.OS === 'android' ? hp(0.5) : hp(1),
    marginVertical: hp(0.7),
    borderRadius: wp(4),
    backgroundColor: colors.lightGrey,
    paddingHorizontal: wp(2),
  },
  placeholderTextColor: {
    fontSize: fontSize(10),
    color: colors.darkBlue,
  },
  dobTextInput: {
    flex: 1,
    paddingVertical: hp(1.5),
    marginRight: 5,
    borderRadius: wp(4),
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    backgroundColor: colors.lightGrey,
    paddingLeft: wp(5),
    textAlignVertical: 'center',
  },
  placeholderStyle: {
    marginHorizontal: wp(3),
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    fontSize: fontSize(17),
  },
  selectedTextStyle: {
    marginHorizontal: wp(3),
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    fontSize: fontSize(17),
  },
  iconStyle: {
    height: wp(7),
    width: wp(7),
    tintColor: colors.darkBlue,
  },
  modalConetent: {
    paddingVertical: wp(2),
  },
  renderContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: wp(5),
    marginHorizontal: wp(1),
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(2),
    backgroundColor: colors.darkBlue,
    height: hp(5),
    borderRadius: wp(3),
  },

  titleHeaderContainer: {
    marginHorizontal: wp(7),
  },
  interestContainer: {
    marginBottom: hp(5),
  },
  interestFlatList: {
    marginVertical: hp(1),
    width: '90%',
    alignSelf: 'center',
  },
  skillTxt: {
    color: colors.white,
    fontSize: fontSize(14),
    fontFamily: fontFamily.bold,
    textAlign: 'center',
  },
  cancleBtn: {
    height: wp(2),
    width: wp(2),
  },

  nextTxt: {
    fontSize: fontSize(17),
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
  },
  btnContainer: {
    width: '90%',
    marginBottom: hp(3),
  },
  okBtnContainer: {
    width: '90%',
    marginVertical: hp(1),
  },
  meetCoachContainer: {
    marginTop: hp(2),
    marginHorizontal: wp(6),
  },
  nameHeaderTxt: {
    color: colors.backgroundRed,
    fontSize: fontSize(20),
    fontFamily: fontFamily.bold,
  },
  editBio: {
    fontSize: fontSize(17),
    fontFamily: fontFamily.openSansBold,
    textAlignVertical: 'top',
    height: hp(13),
    marginVertical: hp(1),
    borderRadius: wp(4),
    paddingTop: hp(1),
    paddingHorizontal: wp(3),
    backgroundColor: colors.inputGrey,
    color: colors.darkBlue,
  },
  customEditBio: {
    fontSize: fontSize(15),
    fontFamily: fontFamily.openSansBold,
    textAlignVertical: 'top',
    color: colors.darkBlue,
    width: '100%',
  },
  coachingFeesTxt: {
    color: colors.darkBlue,
    fontSize: fontSize(20),
    fontFamily: fontFamily.bold,
    marginVertical: hp(2),
  },
  outerFeeContainer: {
    marginTop: hp(1),
    marginBottom: hp(5),
  },
  btnControllerContainer: {
    justifyContent: 'center',
  },
  btnController: {
    position: 'absolute',
    alignSelf: 'center',
  },
  video: {
    width: '100%',
    height: hp(28),
    borderRadius: wp(5),
    marginVertical: hp(1.5),
    alignSelf: 'center',
  },
  videoList: {
    marginVertical: hp(2),
    marginHorizontal: wp(1),
  },
  playBtn: {
    height: wp(10),
    width: wp(10),
    tintColor: colors.white,
  },
  noVideoContainer: {
    height: hp(28),
    alignItems: 'center',
    borderWidth: 0.5,
    color: colors.lightGrey,
    borderRadius: wp(4),
    marginVertical: hp(2),
    justifyContent: 'center',
  },
  noVideoTxt: {
    fontSize: fontSize(20),
    color: colors.lightBlue,
    fontFamily: fontFamily.openSansBold,
  },
  bioTxt: {
    color: colors.darkBlue,
    fontSize: fontSize(17),
    fontFamily: fontFamily.openSansBold,
    marginVertical: hp(1),
  },
  bioContainer: {
    marginVertical: hp(2),
  },
  uploadPic: {
    borderWidth: 2,
    width: '45%',
    height: wp(30),
    borderRadius: wp(4),
  },
  addMoreBtn: {
    borderWidth: 2,
    width: wp(40),
    marginHorizontal: wp(3),
    paddingHorizontal: wp(2),
    // alignSelf: 'center',
    height: wp(28),
    borderRadius: wp(4),
    borderColor: colors.white,
    backgroundColor: colors.lightGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPhotoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  uploadedImg: {
    height: wp(28),
    width: wp(40),
    marginHorizontal: wp(5),
    borderRadius: wp(4),
    alignItems: 'center',
    alignSelf: 'center',
  },
  cardContainer: {
    marginVertical: hp(1),
    marginHorizontal: wp(5),
  },
  input: {
    height: hp(6),
    backgroundColor: colors.inputGrey,
    borderRadius: wp(4),
    marginRight: 8,
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    paddingLeft: wp(4),
    marginVertical: hp(1),
    fontSize: fontSize(15),
  },
  ratesInput: {
    height: hp(6),
    backgroundColor: colors.inputGrey,
    borderRadius: wp(4),
    marginRight: 8,
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    paddingLeft: wp(4),
    marginVertical: hp(1),
    fontSize: fontSize(15),
  },
  feedBackInput: {
    height: hp(13),
    textAlignVertical: 'top',
    backgroundColor: colors.inputGrey,
    borderRadius: wp(4),
    marginRight: 8,
    color: colors.darkBlue,
    fontFamily: fontFamily.openSansBold,
    paddingLeft: wp(4),
    marginVertical: hp(1),
    fontSize: fontSize(15),
    paddingTop: hp(1),
  },
  separatorLine: {
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGreen,
    width: '100%',
    alignSelf: 'center',
    marginVertical: hp(2),
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  spinnerTextStyle: {
    color: colors.white,
    fontSize: fontSize(20),
  },
});
export default style;
